Transaction:
  sources:
    test_json_file_source:
      transform: test_transform
      snippet: test_snippet
      test_snippet: transaction_test.transaction_test
  identifier: uuid
  attributes:
    uuid:
      type: str
      required: True
      sources:
        - test_json_file_source:
            keypath: ['transaction_id']
            required: True
    number_of_widgets:
      type: int
      required: True
      sources:
        - test_json_file_source:
            keypath: ['number_of_widgets']
            required: True
    customer:
      type: str
      required: False
      sources:
        - test_json_file_source:
            keypath: ['customer', 'name']
            required: False

Person:
  sources:
    test_json_file_source:
        transform: test_transform
        snippet: test_snippet
        test_snippet: person_test.person_test
  identifier: name
  attributes:
    name:
      type: str
      required: True
      sources:
        - test_json_file_source:
            keypath: [name]
            required: True
        - some_other_fake_source:
            keypath: [not, a, real, key, path]
            required: False
    age:
      type: int
      required: True
      sources:
        - test_json_file_source:
            keypath: [demographic_data, age]
            required: True
        - some_other_fake_source:
            keypath: [not, a, real, key, path]
            required: False
    total_widgets_purchased:
      type: int
      required: False
      sources:
        - fake_source:
            keypath: [not, really]
            required: False
    big_glasses:
      type: bool
      required: False
      sources:
        - fake_source:
            keypath: [not, really]
            required: False
