Person:
  sources:
    test_json_file_source:
      - transform: test_transform
        snippet: test_snippet
        test_snippet: person_test.person_test
  identifier: name
  attributes:
    name:
      type: str
      required: True
      sources:
        - test_json_file_source:
            keypath: [name]
            required: True
        - some_other_fake_source:
            keypath: [not, a, real, key, path]
            required: False
    age:
      type: int
      required: True
      sources:
        - test_json_file_source:
            keypath: [demographic_data, age]
            required: True
        - some_other_fake_source:
            keypath: [not, a, real, key, path]
            required: False
    big_glasses:
      type: bool
      required: False
      sources:
        - fake_source:
            keypath: [not, really]
            required: False
