mysql_test_store:
  data_store_class: MySQLDataStore
  constructor_options:
    host: MYSQL_HOST
    user: MYSQL_USER
    password: MYSQL_PASSWORD
    database: MYSQL_DATABASE
  contains:
    Person:
      age: [demographics, age]
      name: [demographics, first_name]
