mysql_test_store:
  data_store_class: MySQLDataStore
  constructor_options:
    host: MYSQL_HOST
    user: MYSQL_USER
    password: MYSQL_PASSWORD
    database: MYSQL_DATABASE
  contains:
    Person:
      age: [demographics, age]
      name: [demographics, first_name]
      big_glasses: [demographics, big_glasses]
      total_widgets_purchased: [demographics, total_widgets_purchased]
    Transaction:
      uuid: [transactions, transaction_id]
      number_of_widgets: [transactions, widgets_purchased]
      customer: [transactions, customer_name]
